name: 'Setup GRASS environment'

description: 'Install GRASS on system and setup environment'
author: 'Valentin Lucet'

inputs:
  grass-version:  
    description: 'Version of GRASS to install'
    required: true
    default: '7_8'
  os:
    description: 'Runner OS'
    required: true

outputs:
  installed-grass-version:
    description: 'Version of GRASS installed'
    value: ${{ steps.verify-installed-grass-version.outputs.installed-grass-version }}

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v2
      with:
        repository: 'OSGeo/grass' 
        ref: 'releasebranch_${{ inputs.grass-version }}'
        path: 'grass'

    - run: ls
      shell: bash

    - run: ${{ !startsWith(inputs.os, 'ubuntu') }} || ubuntu.sh
      shell: bash

    - run: ${{ !startsWith(inputs.os, 'mac') }} || echo Hello macOS ${{ inputs.grass-version }}.
      shell: bash

    - id: verify-installed-grass-version
      run: echo "::set-output name=installed-grass-version::$(echo $RANDOM)"
      shell: bash

    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash