name: 'Setup GRASS environment'

description: 'Install GRASS on system and setup environment'
author: 'Valentin Lucet'

inputs:
  grass-version:  
    description: 'Version of GRASS to install'
    required: true
    default: '7_8'
  os:
    description: 'Runner OS'
    required: true

outputs:
  installed-grass-version:
    description: 'Version of GRASS installed'
    value: ${{ steps.verify-installed-grass-version.outputs.installed-grass-version }}

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v2
      with:
        repository: 'OSGeo/grass' 
        ref: 'releasebranch_${{ inputs.grass-version }}'
        path: 'grass'

    # - run: ls grass/.github/workflows -a
    #   shell: bash

    # ${{ !startsWith(inputs.os, 'ubuntu') }} || setup-grass/ubuntu.sh

    - id: setup-env
      run: |
        mkdir $HOME/install
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/install/lib" >> $GITHUB_ENV
      shell: bash

    - id: build-grass-ubuntu
      run: |
        ${{ !startsWith(inputs.os, 'ubuntu') }} || (setup-grass/ubuntu.sh && \
        echo "$HOME/install/bin" >> $GITHUB_PATH && \
        echo $GITHUB_PATH && \
        $HOME/install/bin/grass78 -h \
        grass/.github/workflows/test_thorough.sh)
      shell: bash

    - id: test-grass-ubuntu
      run: |
        grass78 --tmp-location XY --exec g.extension g.download.location
        grass78 --tmp-location XY --exec g.download.location url=http://fatra.cnr.ncsu.edu/data/nc_spm_full_v2alpha2.tar.gz dbase=$HOME
        grass78 --tmp-location XY --exec python3 -m grass.gunittest.main --grassdata $HOME --location nc_spm_full_v2alpha2 --location-type nc --min-success 90
      shell: bash

    - run: ${{ !startsWith(inputs.os, 'mac') }} || echo Hello macOS ${{ inputs.grass-version }}.
      shell: bash

    # - id: verify-installed-grass-version
    #   run: echo "::set-output name=installed-grass-version::$(echo $RANDOM)"
    #   shell: bash

    # - run: ${{ github.action_path }}/goodbye.sh
    #   shell: bash
    