name: 'Setup GRASS environment'

description: 'Install GRASS on system and setup environment'
author: 'Valentin Lucet'

inputs:
  grass-version:  
    description: 'Version of GRASS to install'
    required: true
    default: '8_0'
  os:
    description: 'Runner OS'
    required: true

outputs:
  installed-grass-version:
    description: 'Version of GRASS installed'
    value: ${{ steps.verify-installed-grass-version.outputs.installed-grass-version }}

runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v2
      with:
        repository: 'OSGeo/grass' 
        ref: 'releasebranch_${{ inputs.grass-version }}'
        path: 'grass'

    # - run: ls grass/.github/workflows -a
    #   shell: bash

    # ${{ !startsWith(inputs.os, 'ubuntu') }} || setup-grass/ubuntu.sh

    - id: setup-env
      run: |
        mkdir $HOME/install
        echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/install/lib" >> $GITHUB_ENV
      shell: bash

    - id: build-grass-ubuntu
      run: |
        ${{ !startsWith(inputs.os, 'ubuntu') }} || (setup-grass/ubuntu.sh && \
        echo "$HOME/install/bin" >> $GITHUB_PATH)
      shell: bash

    - id: test-grass-ubuntu
      run: |
        ls $HOME/install/bin &&
        ${{ !startsWith(inputs.grass-version, '7') }} || GRASS=$HOME/install/bin/grass78 && \
        ${{ !startsWith(inputs.grass-version, '8') }} || GRASS=$HOME/install/bin/grass &&
        ${{ !startsWith(inputs.os, 'ubuntu') }} || ($GRASS -h && \
        $GRASS --tmp-location EPSG:4326 --exec g.region res=0.1 -p)
      shell: bash

    - id: build-grass-windows
      run: |
        ${{ !startsWith(inputs.os, 'windows') }} || setup-grass/windows.ps1
      shell: pwsh

    # - id: test-grass-windows
    #   run: |
    #     ${{ !startsWith(inputs.os, 'windows') }} || 
    #   shell: bash

    - run: ${{ !startsWith(inputs.os, 'mac') }} || echo Hello macOS ${{ inputs.grass-version }}.
      shell: bash
    
    - run: ${{ !startsWith(inputs.os, 'windows') }} || echo Hello windows ${{ inputs.grass-version }}.
      shell: bash

    # - id: verify-installed-grass-version
    #   run: echo "::set-output name=installed-grass-version::$(echo $RANDOM)"
    #   shell: bash

    # - run: ${{ github.action_path }}/goodbye.sh
    #   shell: bash

    #  && \
    #         echo $GITHUB_PATH && \
    #         $HOME/install/bin/grass78 -h \
    #         grass/.github/workflows/test_thorough.sh)