on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: vlucet/grass-actions/setup-grass@v1.04
        with:
          grass-version: '7'
      - run: echo installed-grass-version ${{ steps.foo.outputs.installed-grass-version }}
        shell: bash