on: [push]

jobs:
  install-grass:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        grass: [ '7_8', '8_0' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
    
    name: Install GRASS
    steps:

      - uses: actions/checkout@v2

      - id: setup
        uses: vlucet/grass-actions/setup-grass@main
        with:
          grass-version: ${{ matrix.grass }}
          os: ${{ matrix.os }}

      - run: echo installed-grass-version ${{ steps.setup.outputs.installed-grass-version }}
        shell: bash