on: [push]

jobs:
  install-grass:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        grass: [ '8_0' ] # , '8_0' 
        os: [ 'ubuntu-latest' , 'windows-latest' ] # , 'windows-latest', 'macOS-latest'
    
    name: Install GRASS
    steps:

      - uses: actions/checkout@v2

      - id: setup
        uses: vlucet/grass-actions/setup-grass@main
        with:
          grass-version: ${{ matrix.grass }}
          os: ${{ matrix.os }}

      # - run: echo ${{ steps.setup.outputs.installed-grass-version }}
      #   shell: bash