on: [push]

jobs:
  install-grass:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        grass: [ '7', '8' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
    
    name: Install GRASS
    steps:

      - uses: actions/checkout@v2

      - id: foo
        uses: vlucet/grass-actions/setup-grass@v1.10
        with:
          grass-version: ${{ matrix.grass }}
          os: ${{ matrix.os }}

      - run: echo installed-grass-version ${{ steps.foo.outputs.installed-grass-version }}
        shell: bash